FROM node:20-slim as build

LABEL maintainer="you@example.com"
LABEL description="Shuffle Frontend"

RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/Shuffle/Shuffle.git /app

WORKDIR /app/frontend
RUN npm install && npm run build

# --- runtime container ---
FROM nginx:stable-alpine
COPY --from=build /app/frontend/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
